name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      backend--tag_name: ${{ steps.release.outputs.backend--tag_name }}
      backend--release_created: ${{ steps.release.outputs.backend--release_created }}
      frontend--tag_name: ${{ steps.release.outputs.frontend--tag_name }}
      frontend--release_created: ${{ steps.release.outputs.frontend--release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

  release-backend:
    if: ${{ needs.release-please.outputs.backend--release_created == 'true' }}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - name: Zip backend source code
        run: zip -r backend-${{ needs.release-please.outputs.backend--tag_name }}.zip backend
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-source-${{ needs.release-please.outputs.backend--tag_name }}
          path: backend-${{ needs.release-please.outputs.backend--tag_name }}.zip
      


  release-frontend:
    if: ${{ needs.release-please.outputs.frontend--release_created == 'true' }}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - name: Zip Frontend Folder
        run: zip -r frontend-${{ needs.release-please.outputs.frontend--tag_name }}.zip frontend
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ needs.release-please.outputs.frontend--tag_name }}
          path: frontend-${{ needs.release-please.outputs.frontend--tag_name }}.zip
